spring:
  application:
    name: bff
  graphql:
    path: /graphql
    schema:
      locations: classpath:graphql/
    websocket:
      path: /graphql

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      service: bff

pennywise:
  security:
    oidc:
      audience: ${PENNYWISE_SECURITY_OIDC_AUDIENCE:}
