spring:
  application:
    name: accounts
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      service: accounts

pennywise:
  security:
    oidc:
      audience: ${PENNYWISE_SECURITY_OIDC_AUDIENCE:}
