# Local domain socket connections require SCRAM-SHA-256 password authentication
local   all             all                                      scram-sha-256
host    all             all             0.0.0.0/0                scram-sha-256
host    replication     squarewise_replica 0.0.0.0/0             scram-sha-256
