services:
  postgres:
    extends:
      file: docker-compose.yml
      service: postgres
  rabbitmq:
    extends:
      file: docker-compose.yml
      service: rabbitmq
  mailpit:
    extends:
      file: docker-compose.yml
      service: mailpit
